### PR TITLE
Added jbuabbud to pullapprove users

### PR DESCRIPTION
**Pull request by ghost**
I've added myself to the list of users who can approve pull requests.

### CODE REVIEW

**Review by mcovarr — APPROVED** [review]

**Comment by mcovarr** [comment]
Do we know why we're seeing this message? `.pullapprove.yml proposed by this PR is invalid`

**Comment by ghost** [comment]
I have some guesses, seems to be related to pullapprove which is a plugin that integrates with github. I think it's safe to ignore. It has an outdated list collaborators so it thinks I'm unauthorized.

**Comment by cjllanwarne** [comment]
pullapprove needed a kick to refresh it's collaborators list. 👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/winstanley/pull-request/42/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/winstanley)

**Comment by cjllanwarne** [comment]
This PR looks good now, go ahead and merge when ready. I'd also go ahead and add yourself to Cromwell.

**Pull request merged**
