### PR TITLE
target all jetbrains applications

### PR DESCRIPTION
**Pull request by danbills**
easy peasy

### CODE REVIEW

**Comment by geoffjentry** [comment]
👍 

That's some low hanging fruit :)

[Approved with PullApprove](https://pullapprove.com/broadinstitute/winstanley/pull-request/6/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/winstanley)

**Comment by ruchim** [comment]
👍 


[Approved with PullApprove](https://pullapprove.com/broadinstitute/winstanley/pull-request/6/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/winstanley)

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/winstanley/pull-request/6/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/winstanley)

**Comment by cjllanwarne** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/winstanley/pull-request/6/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/winstanley)

**Pull request merged**
